### ISSUE TITLE
Q: What is our bottom line PS5 or PSx?

### ISSUE THREAD

**Issue by TiddlyTweeter** [Marxsal/polly#20]
I'm writing code where I need to be clearer if we support only 5+, or support lower versions. It matters in that its either "-eq 5" OR "-lt 6". Are we clear what happens on 4? And if its worth supporting?

**Comment by Marxsal** [comment]
In theory, everyone after December will be on FF 5+. 

Not sure what happens on 4. We had something that didn't render right on your menus. I upgraded to 5 to match you, perhaps too hastily. It's not possible apparently to run PS4 and PS5 at the same time, although it is possible to run PS5 and PS6/Core at the same time.

Are you concerned that your students will still be running 4? That would mean they're on Win 7 machines ... is that likely? (yeah, I'm on 7, but I try to stretch my machine's life cycle to more than a half-decade).

**Comment by TiddlyTweeter** [comment]
You can close this issue once you read it. 

_I go with with thought we do PS5+_ .  IF we got missives about 4 I'd be surprised. 

And I want to avoid looking at anything that is marginal at the moment. We have a lot on our plate with 5 / 6 already.
