### ISSUE TITLE
End User Issues

### ISSUE THREAD

**Issue by TiddlyTweeter** [Marxsal/polly#3]
- Coping with BACKUP EXCESS GROWTH

There is STRONG correlation between growth of excess backups and Auto-Restore timing. 

IF a user is a happy typist with auto-save on to downloads, with very regular Polly restore, they may well have a red-face in the morning--with vast numbers of backups.

Q: _IS this about advising them or setting different defaults?_

_Polly Once_, in some ways makes much sense. More than Auto Restore, in a way. 

Of course you need to KNOW to run it. But it keeps backups and restores _but of just what you need when you need it_. 

_Since_ download saving is already occurring the merits of "auto" could be over-stated. Its distinct downside is potential vast proliferation of redundant backups & zips.

**Comment by Marxsal** [comment]
Yes, I've been using polly-once a lot. The main thing is to remember to use it *before* reloading your browser, or else you will be tempted into making changes on an outdated TW file.

**Comment by TiddlyTweeter** [comment]
If we had a batch file to once then launch wiki ...  ?

**Comment by TiddlyTweeter** [comment]
Here is an actual scenario. I forgot I was on web looking at polly.html. Made changes. Realised but didn't have time so saved & edited the download saved polly.html (2)  in another browser. Saved more work to polly.html (2) (2). Got my act together. Restored once. Wiki restored. Back to edit as normal. 

Downloads as hub has big upsides.

**Comment by TiddlyTweeter** [comment]
Recent discussion covers this territory better. So Close.
